name: Linters and tests
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
    - uses: actions/checkout@v4
    - id: setup-uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install Dependencies
      if: steps.setup-uv.outputs.cache-hit != 'true'
      run: uv sync --all-extras
    - name: Run linters
      run: uv run ruff check ya_tracker_client examples tests
  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        python-version: [ "3.10", "3.13" ]
        pydantic-version: [ "pydantic-v1", "pydantic-v2" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - id: setup-uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          activate-environment: true
      - name: Install Dependencies
        if: steps.setup-uv.outputs.cache-hit != 'true'
        run: uv sync --all-extras
      - name: Install Pydantic v1
        if: matrix.pydantic-version == 'pydantic-v1'
        run: uv pip install "pydantic>=1.10.0,<2.0.0"
      - name: Install Pydantic v2
        if: matrix.pydantic-version == 'pydantic-v2'
        run: uv pip install --prerelease=disallow "pydantic>=2.0.0,<3.0.0"
      - run: mkdir coverage
      - name: Test
        run: uv run pytest --verbosity=2 --showlocals --log-level=DEBUG
