name: Linters and tests
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint code
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install --upgrade pip
    - run: make install
    - run: make lint
  test:
    runs-on: ubuntu-latest
    name: Run tests
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip
      - run: make install
      - run: make test
